version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
      nodejs: 18
    commands:
      - echo "Installing AWS SAM CLI..."
      - pip install --upgrade pip
      - pip install aws-sam-cli
      
  pre_build:
    commands:
      - echo "Validating SAM template..."
      - sam validate --template template.yaml
      - echo "Template validation successful!"
      
  build:
    commands:
      - echo "Building SAM application..."
      - sam build --template template.yaml
      - echo "Build completed successfully!"
      
      # Build frontend
      - echo "Building frontend..."
      - cd frontend
      - npm install
      - npm run build
      - cd ..
      
  post_build:
    commands:
      - echo "Packaging application..."
      - |
        sam package \
          --template-file .aws-sam/build/template.yaml \
          --s3-bucket $BUILD_BUCKET \
          --output-template-file packaged.yaml
      - echo "Application packaged successfully!"

artifacts:
  files:
    - packaged.yaml
    - template.yaml
    - frontend/dist/**/*
  name: build-artifacts